# Generated by Django 6.1.1 on 2026-09-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_create_at_order_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='prduct_name',
            new_name='product_name',
        ),
    ]
