# Generated by Django 6.1.1 on 2026-09-05 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_prduct_name_order_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='traking_number',
            new_name='tracking_number',
        ),
    ]
