# Generated by Django 6.1.1 on 2026-09-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_traking_number_order_tracking_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refundrequest',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
