# Generated by Django 6.1.1 on 2026-09-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_message_delete_massage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('modle', 'Model')], max_length=20),
        ),
    ]
