# Generated by Django 6.1.1 on 2026-09-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_message_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('model', 'Model')], max_length=20),
        ),
    ]
