# Generated by Django 6.1.1 on 2026-09-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_processedevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='tavily_calls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversation',
            name='total_input_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversation',
            name='total_output_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
