# Generated by Django 6.1.1 on 2026-09-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_conversation_tavily_calls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='correlation_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
