# Generated by Django 6.1.1 on 2026-09-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_message_correlation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=255)),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
            ],
            options={
                'unique_together': {('document', 'chunk_index')},
            },
        ),
    ]
